export const INPUT_CHANGE = "INPUT_CHANGE";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

//SINGUP
// export const FORM_SUBMIT = "FORM_SUBMIT";
// export const FORM_SUBMIT_SUCCESS = "FORM_SUBMIT_SUCCESS";
// export const FORM_SUBMIT_FAILURE = "FORM_SUBMIT_FAILURE";

// export const GET_USERS = "GET_USERS";
// export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
// export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

//export const INPUT_CHANGE = "INPUT_CHANGE";
export const GET_SIGNUP = "GET_SIGNUP";
export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";
export const GET_SIGNUP_FAILURE = "GET_SIGNUP_FAILURE";

export const LOGIN = "LOGIN";
// export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export const LOGIN_FAILURE = "LOGIN_FAILURE";

//brands

export const GET_BRANDS = "GET_BRANDS";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const GET_BRANDS_FAILURE = "GET_BRANDS_FAILURE";

export const GET_BRANDS_DETAILS = "GET_BRANDS_DETAILS";
export const GET_BRANDS_DETAILS_SUCCESS = "GET_BRANDS_DETAILS_SUCCESS";
export const GET_BRANDS_DETAILS_FAILURE = "GET_BRANDS_DETAILS_FAILURE";

//Chocolates
export const GET_CHOCOLATE = "GET_CHOCOLATE";
export const GET_CHOCOLATE_SUCCESS = "GET_CHOCOLATE_SUCCESS";
export const GET_CHOCOLATE_FAILURE = "GET_CHOCOLATE_FAILURE";

export const GET_CHOCOLATE_DETAILS = "GET_CHOCOLATE_SUCCESS_DETAILS";
export const GET_CHOCOLATE_DETAILS_SUCCESS = "GET_CHOCOLATE_DETAILS_SUCCESS";
export const GET_CHOCOLATE_DETAILS_FAILURE = "GET_CHOCOLATE_DETAILS_FAILURE";

//login
export const GET_INPUT = "GET_INPUT";
export const GET_SUBMIT = "GET_SUBMIT";
export const GET_LOGINSUCCESS = "GET_LOGINSUCCESS";
export const GET_LOGINFAILURE = "GET_LOGINFAILURE";
///search
export const GET_SEARCH = "GET_SEARCH";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAILURE = "GET_SEARCH_FAILURE";
export const GET_SEARCH_VALUE = "GET_SEARCH_VALUE";
